FROM python:3.12-slim

WORKDIR /app


COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

COPY pyproject.toml uv.lock ./


RUN uv pip install --system --index-url https://pypi.tuna.tsinghua.edu.cn/simple -e .[dev]


COPY main.py ./
COPY tests/ ./tests/

CMD ["pytest", "tests/", "-v"]